app/account/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'account'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView, name='logout'),
]

app/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog_app.urls')),
    path('accounts/', include('account.urls')),
    path('admin/', admin.site.urls),
]

app/blog_app/urls.py
from django.urls import path
from .views import HomeView, ProfileView

app_name = 'blog'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

app/account/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _


class AccountManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Account(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=255, unique=False)
    followers = models.ManyToManyField('self', related_name='followers', blank=True)
    birth_date = models.DateField(blank=True, null=True)
    first_name = models.CharField(max_length=255, blank=True, default='')
    second_name = models.CharField(max_length=255, blank=True, default='')
    status = models.CharField(max_length=255, blank=True, default='')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = AccountManager()

app/account/forms.py
from django import forms
from django.contrib.auth import get_user_model


class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput
        (attrs={'class': 'text', 'name': 'Username', 'placeholder': 'Username'}))

    email = forms.EmailField(widget=forms.EmailInput
        (attrs={'class': 'text email', 'name': 'email', 'placeholder': 'Email'}))

    password = forms.CharField(widget=forms.PasswordInput
        (attrs={'class': 'text password', 'name': 'password', 'placeholder': 'Password'}))

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(user.password)  # set password properly before commit
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password')


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput
        (attrs={'class': 'text email', 'name': 'email', 'placeholder': 'Email'}))

    password = forms.CharField(widget=forms.PasswordInput
        (attrs={'class': 'text password', 'name': 'password', 'placeholder': 'Password'}))

app/account/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import View, FormView
from .forms import RegisterForm, LoginForm


class RegisterView(View):
    @staticmethod
    def get(request):
        if request.user.is_authenticated:
            return redirect('blog:home')
        form = RegisterForm()
        return render(request, 'account/register.html', {'form': form})

    @staticmethod
    def post(request):
        context = {}
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            login(request, user)
            if user is not None:
                return redirect('blog:home')
        context['form'] = form
        return render(request, 'account/register.html', context)


class LoginView(View):
    @staticmethod
    def get(request):
        if request.user.is_authenticated:
            return redirect('blog:home')
        form = LoginForm()
        return render(request, 'account/login.html', {'form': form})

    @staticmethod
    def post(request):
        context = {}
        form = LoginForm(request.POST)
        if form.is_valid():
            credentials = form.cleaned_data
            user = authenticate(username=credentials['email'],
                                password=credentials['password'])
            if user is not None:
                login(request, user)
                return redirect('blog:home')
        context['form'] = form
        return redirect('account:login')


def LogoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('account:login'))

app/blog_app/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model


class HomeView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def get(self, request):
        return render(request, 'blog_app/home_page.html')


class ProfileView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def get(self, request):
        # User = get_user_model()
        context = {}
        user = request.user
        context['user'] = user
        context['followers'] = user.followers.all()[:5]
        return render(request, 'blog_app/profile_page.html', context=context)

app/blog_app/templates/blog_app/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://kit.fontawesome.com/9d3bd7c6e3.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}Blog{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'blog:home' %}">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:profile' %}">Profile</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'account:logout' %}">
            <button class="btn btn-danger my-2 my-sm-0 mr-2 pl-4 pr-4" type="submit">Log Out</button>
        </form>
    </div>
</nav>

<div class="content mt-5">
    <div class="container">
        {% block content %}
            <h3>No Content</h3>
        {% endblock %}
    </div>
</div>

</body>
</html>

app/blog_app/templates/blog_app/includes/sidebar.html
<div class="sidebar col-3">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="btn btn-primary nav-link my-2 my-sm-0 mr-2 pl-2 pr-2 active text-white" href="#">Add Post</a>
        </li>
    </ul>
</div>